"""Wiki → Markdown 导出。

把一份 WikiDocument 序列化成单个 .md 文件：
- 按 index.tree 的顺序递归遍历，拼接所有页面正文
- 每页前插一个 HTML 锚点 `<a id="<page_id>"></a>`，供文内 `#wiki:<id>` 跳转
- 文内 `#wiki:<id>` → `#<id>`
- 文内 `#code:ref_N` → ``` `path:L起-L止` ``` 行内 code（基于 metadata.code_refs）
- category 节点作为一级分组标题，无正文
"""

from __future__ import annotations

import re
from io import StringIO

from backend.models.wiki_models import PageMetadata, WikiDocument, WikiPage

_WIKI_LINK_RE = re.compile(r"\]\(#wiki:([A-Za-z0-9_]+)\)")
_CODE_LINK_RE = re.compile(r"\[([^\]]+)\]\(#code:([A-Za-z0-9_]+)\)")


def export_to_markdown(doc: WikiDocument) -> str:
    """产出单份 Markdown 字符串。"""
    buf = StringIO()
    id_to_page = {p.id: p for p in doc.pages}

    # 页首元信息
    buf.write(f"<!-- Generated by CoReviewer at {doc.generated_at} -->\n\n")

    # 从 index.root 递归遍历。顶层 overview 作 H1，其下 category 也作 H1，
    # chapter/module/topic 作 H2。category 无 content_md，只打标题。
    _visit(
        page_id=doc.index.root,
        level=1,
        doc=doc,
        id_to_page=id_to_page,
        buf=buf,
        visited=set(),
    )

    return buf.getvalue().rstrip() + "\n"


def _visit(
    *,
    page_id: str,
    level: int,
    doc: WikiDocument,
    id_to_page: dict[str, WikiPage],
    buf: StringIO,
    visited: set[str],
) -> None:
    if page_id in visited:
        return
    visited.add(page_id)

    node = doc.index.tree.get(page_id)
    page = id_to_page.get(page_id)
    if node is None or page is None:
        return

    # 锚点（供文内 #wiki:<id> 跳转到）
    buf.write(f'<a id="{page_id}"></a>\n\n')

    # 标题：category/overview 用当前 level；子页用 level+1
    title_prefix = "#" * min(max(level, 1), 6)
    buf.write(f"{title_prefix} {page.title}\n\n")

    # category 节点没有正文，跳过 content 渲染
    if page.type != "category" and page.content_md:
        body = _transform_links(page.content_md, page.metadata)
        buf.write(body.rstrip() + "\n\n")

    # 递归子节点。category 下的子节点与 category 同级（都是 H1 的"类"，子是 H2 的"章"）
    # overview 的直接子是 3 个 category，保持 level=1；category 的直接子则是 level=2。
    for child_id in node.children:
        # overview(level=1) → children 是 category(level=1, 因为 category 也是大类标题)
        # category(level=1) → children 是 chapter/module/topic(level=2)
        child_level = level + 1 if page.type == "category" else level
        # 但 overview 的孩子是 category，应保持 level=1（参考站也是这样分大类）
        _visit(
            page_id=child_id,
            level=child_level,
            doc=doc,
            id_to_page=id_to_page,
            buf=buf,
            visited=visited,
        )


def _transform_links(content_md: str, metadata: PageMetadata) -> str:
    """把 #wiki:<id> 和 #code:<ref> 转成离线可读的形式。"""

    # #wiki:<id> → #<id>
    out = _WIKI_LINK_RE.sub(lambda m: f"](#{m.group(1)})", content_md)

    # [text](#code:ref_N) → [text]（附 `path:Lstart-Lend`）
    # 拿不到 ref 就保留原文
    def _code_sub(match: re.Match[str]) -> str:
        text = match.group(1)
        ref_id = match.group(2)
        ref = metadata.code_refs.get(ref_id)
        if not ref:
            return match.group(0)
        loc = f"{ref.file}:L{ref.start_line}-L{ref.end_line}"
        return f"**{text}**（`{loc}`）"

    out = _CODE_LINK_RE.sub(_code_sub, out)
    return out
